language: php

php:
  - 5.5
  - 5.4
  - 5.3

branches:
  only:
    - master

before_script:
  - sudo apt-get update
  - sudo apt-get install php-pear
  - pear channel-discover pear.phpqatools.org
  - pear install -f phpqatools/phpqatools
  - phpenv rehash
       
script:
  - phpcs --standard=phpcs_ruleset.xml .
  - php index.php