language: php

php:
  - 5.5
  - 5.4
  - 5.3

branches:
  only:
    - master

before_script:
  - pear channel-discover pear.phpqatools.org
  - pear install -f phpqatools/phpqatools
  - phpenv rehash
       
script:
  - ant travis
